### ISSUE TITLE
Cannot connect with discord-cli.

### ISSUE THREAD

**Issue by Dark-Feather** [Rivalo/discord-cli#37]
After setting up what I thought was a sane configuration, I get this message.

discord-cli - version: v0.3.0-DEVELOP

*Starting Session...2017/03/07 08:54:50 Session Failed
2017/03/07 08:54:50 Unable to fetch discord authentication token. HTTP 400 Bad Request, {"email": ["Not a well formed email address."]}

**Comment by RickvanLoo** [comment]
Can't do anything with this issue. I do not know what your sane configuration is. Others do not have this problem, so it's on your end.

**Comment by Dark-Feather** [comment]
I have tried:
{"username":"DarkFeather","password":"REDACTED","email":"REDACTED","messagedefault":true,"messages":10}

And: 
{"username":"DarkFeather","password":"REDACTED","messagedefault":true,"messages":10}

**Comment by RickvanLoo** [comment]
In the README it says:

| Setting       | Function         |
| ------------- |-------------|
| username      | Discord Username (emailaddress) |
| password      | Discord Password |
| messagedefault| (true or false) Display messages automatically|
| messages   | Amount of Messages kept in memory |

You can't log in with just your Discord username even in the official client, which is btw of the form Name#0000 
'Email' is not a configuration option the client filters upon. Adding any new options in the configuration will either trigger unforeseen errors or doesn't change a thing.

A sane configuration following the instruction in the README would be:

>{"username":"DarkFeather@DarkFeather.com","password":"REDACTED","messagedefault":true,"messages":10}

Next time please use the Discord server for help or read the README. Github Issues are not for support.

**Comment by Dark-Feather** [comment]
Yeah, I'm dumb... I read over the wiki and didn't look close enough. Sorry for the clutter.
